
OUTPUT_DIR: "./output"
MODEL:
  WEIGHTS: ""
  HOURGLASS:
    N: 5
    DIMS: [256, 256, 384, 384, 384, 512]
    MODULES: [2, 2, 2, 2, 2, 4]
    CNV_DIM: 256
    NSTACK: 2
    OUT_FEATURES: ['hg1', 'hg2']

SOLVER:
  IMS_PER_BATCH: 16
  MAX_ITER: 90000
DATASETS:
  TRAIN: ("visdrone_train",)
  TEST: ("visdrone_val",)

TEST:
  AUG:
    ENABLED: True
    MIN_SIZES: (400, 500, 600, 700, 800, 900, 1000, 1100, 1200)
    MAX_SIZE: 2000
    FLIP: True
