__BASE__: "/home/haida_sunxin/lqx/code/llseg/configs/configs_files/detection/base_RetinaNet.yaml"

OUTPUT_DIR: "./Retina_patch"
MODEL:
  BUILDER: "base_retina_builder"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 12
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [16, 32, 64, 128]]"]
  RETINANET:
    NUM_CLASSES: 12
    IN_FEATURES: ['p3', 'p4', 'p5', 'p6']
    SOFT_NMS_ENABLE: False
    SOFT_NMS_METHOD: "linear"
    SOFT_NMS_SIGMA: 0.5
    SOFT_NMS_PRUNE: 0.001

DATASETS:
  TRAIN: ("visdrone_patch_train",)
  TEST: ("visdrone_patch_val",)

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 5000

TEST:
  DETECTIONS_PER_IMAGE: 500