__BASE__: "/home/haida_sunxin/lqx/code/llseg/configs/configs_files/detection/base_RCNN_FPN.yaml"

OUTPUT_DIR: "./Cascade_r50"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  FPN:
    NORM: "SyncBN"
  ROI_HEADS:
    NAME: "CascadeROIHeads"
    NUM_CLASSES: 80
    SOFT_NMS_ENABLED: False
    SOFT_NMS_METHOD: "linear"
    SOFT_NMS_SIGMA: 0.5
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
    NORM: "SyncBN"
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
  RESNETS:
    NORM: "SyncBN"
#    STRIDE_IN_1X1: True  # this is a C2 model
#    NUM_GROUPS: 1
#    WIDTH_PER_GROUP: 8
    DEPTH: 50
    DEFORM_ON_PER_STAGE: (False, False, False, False)
    DEFORM_MODULATED: False
    DEFORM_NUM_GROUPS: 1
SOLVER:
  IMS_PER_BATCH: 4
  MAX_ITER: 1000
  STEPS: (15000, 18000)
DATASETS:
  TRAIN: ("coco_2017_val",)
  TEST: ("coco_2017_val",)

TEST:
  DETECTIONS_PER_IMAGE: 500
  AUG:
    ENABLED: True
    MIN_SIZES: (600, 700, 800, 900, 1000, 1100, 1200)
    MAX_SIZE: 2000
    FLIP: True
