__BASE__: "/home/haida_sunxin/lqx/code/llseg/configs/configs_files/detection/base_RetinaNet.yaml"

OUTPUT_DIR: "./Retina"
MODEL:
  BUILDER: "base_retina_builder"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50

DATASETS:
  TRAIN: ("visdrone_train",)
  TEST: ("visdrone_val",)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 5000