__BASE__: "/home/haida_sunxin/lqx/code/llseg/configs/configs_files/detection/base_RCNN_FPN.yaml"

OUTPUT_DIR: "./Out_X-101-32x8d_test"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  ROI_HEADS:
    NUM_CLASSES: 12
    NMS_THRESH_TEST: 0.7
    SOFT_NMS_ENABLED: True
    SOFT_NMS_METHOD: "linear"
    SOFT_NMS_SIGMA: 0.5
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
    DEFORM_ON_PER_STAGE: (False, True, True, True)
    DEFORM_MODULATED: True
    DEFORM_NUM_GROUPS: 1
SOLVER:
  IMS_PER_BATCH: 16
  MAX_ITER: 90000
DATASETS:
  TRAIN: ("visdrone_train",)
  TEST: ("visdrone_val",)
DATALOADER:
  NUM_WORKERS: 16
TEST:
  DETECTIONS_PER_IMAGE: 500
  AUG:
    ENABLED: True
    MIN_SIZES: (400, 500, 600, 700, 800, 900, 1000, 1100, 1200)
    MAX_SIZE: 2000
    FLIP: True
