__BASE__: "/home/haida_sunxin/szq/spnet/configs/configs_files/sem_seg/seg_base.yaml"

OUTPUT_DIR: './spnet2'

MODEL:
  STRIDE: 8
  #WEIGHTS: "/home/haida_sunxin/lqx/code/llseg/ext/models/baseline_res_101.pth"

  HEAD:
    NAME: "spnet_builder"
SOLVER:
  BASE_LR: 0.005
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  POWER: 0.9
  IMS_PER_BATCH: 8
  MAX_ITER: 40000

TEST:
  AUG: False
  SCALES: [0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0]
  FLIP: False
