OUTPUT_DIR: "./fcos_r50_darts_layer1"
MODEL:
  BUILDER: "base_onesstageanchorfree_builder"
  BACKBONE:
    NAME: "retinanet_resnet_fpn_builder"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  ANCHORFREE_HEADS:
    NAME: "fcos_head_builder"
  FCOS_HEADS:
    FPN_STRIDES: [8, 16, 32, 64, 128]
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
    SIZES_OF_INTEREST: [64, 128, 256, 512]
    POST_NMS_TOPK_TRAIN: 256
    NUM_CLS_CONVS: 4
    NUM_BBOX_CONVS: 4
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000